apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: oo3f4ry14-java-quarkus
  janus-idp.io/tekton: oo3f4ry14-java-quarkus
  backstage.io/kubernetes-id: oo3f4ry14-java-quarkus
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: oo3f4ry14-java-quarkus
resources:
- deployment.yaml
- route.yaml
- service.yaml
