apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: oo3f4ry14-java-quarkus-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/oo3f4ry14-java-quarkus-gitops